apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: peachycloudsecurity-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: peachycloudsecurity-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: peachycloudsecurity-clusterrole
  apiGroup: rbac.authorization.k8s.io
